---
fixtures:
  repositories:
    stdlib: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
    yum: 'https://github.com/voxpupuli/puppet-yum.git'
    yumrepo_core: 'https://github.com/puppetlabs/puppetlabs-yumrepo_core.git'
  symlinks:
    openvpnas: '#{source_dir}'


