---
require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  Exclude:
    - 'vendor/**/*'
    - 'pkg/**/*'
    - '.vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'Gemfile'
    - 'Rakefile'

# Puppet modules are generally documentation-heavy
Metrics/BlockLength:
  Enabled: false

# RSpec tests can have long describe blocks
RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Layout/LineLength:
  Max: 120


